### PR TITLE
add Namednote documentation

### PR DESCRIPTION
**Pull request by NeroBlackstone**

### CODE REVIEW

**Comment by NeroBlackstone** [comment]
Seems ci build failed 😔, I don't know how to build site locally so I don't test it.

https://github.com/JuliaMusic/JuliaMusic_documentation.jl/actions/runs/5213268091/jobs/9408038538

**Comment by Datseris** [comment]
works now!

**Comment by Datseris** [comment]
> I don't know how to build site locally so I don't test it.

Run `docs/make.jl`.

**Comment by NeroBlackstone** [comment]
> > I don't know how to build site locally so I don't test it.
> 
> Run `docs/make.jl`.

Thank you very much! I will test it next time 😉

**Pull request merged**
